### ISSUE TITLE
Keep raw body attached to the server request produced by the worker

### ISSUE THREAD

**Issue by jjsaunier** [spiral/roadrunner-http#4]
https://github.com/spiral/roadrunner-http/blob/0eb0bc93f16ff8130fd0aaf31f6d87000bf2a605/src/PSR7Worker.php#L195

Due to the current implementation, if request content type is `application/x-www-form-urlencoded` we only retrieved parsed content however in some cases we want to keep the raw body, as main reason there are multiple rfc arround x-www-form-urlencoded and it require to format it back from the parsed data, format is altered in some situation and unable to guess back the RFC used to forward to upstream / external system the exact same body was sent

If body could be parsed, it should not prevent from getting raw body through `$request->getBody()->getContents()`, also as side effect, since the `$stream` attrbitute on `$request` stay `null`, `$request->getSize()` is always 0 whereas body is present (all functions of request relying on stream are affected, isEof etc ...)

**Comment by jjsaunier** [comment]
Well, didn't see https://github.com/spiral/roadrunner-http/pull/3 and duplicate of https://github.com/spiral/roadrunner-http/issues/2

**Comment by SerafimArts** [comment]
Ok then I'll close this issue as a duplicate. Sorry for the delay.
