### ISSUE TITLE
Enforce or Prevent Type for header parsing

### ISSUE THREAD

**Issue by jjsaunier** [spiral/roadrunner-http#7]
From the code here: https://github.com/spiral/roadrunner-http/blob/master/src/PSR7Worker.php#L136

`$key` is passed straight to `str_replace` which accepts `string|array` and not `int` which can result in

```
Fatal Error (E_ERROR): Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, int given in /opt/project/vendor/spiral/roadrunner-http/src/PSR7Worker.php:137
```

As you can imagine, this could have big consequences for rr users. You should enforce the type or prevent it (skipping it)

**Comment by SerafimArts** [comment]
Done: https://github.com/spiral/roadrunner-http/releases/tag/v2.0.3
