### ISSUE TITLE
RR altered body payload

### ISSUE THREAD

**Issue by jjsaunier** [spiral/roadrunner-http#9]
The given example sent to a RR application: 

 ```php
 <?php

$curl = curl_init();

curl_setopt_array($curl, array(
    CURLOPT_URL => "https://app.local", // replace to RR endpoint
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_SSL_VERIFYPEER => 0,
    CURLOPT_SSL_VERIFYPEER => 0,
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_HTTPHEADER => array('Content-Type: application/x-www-form-urlencoded'),
    CURLOPT_POSTFIELDS =>"foo=bar&baz=bar",
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```

On application (The psr/http psr7 factory does not matter, nylon, guzzle gave same result)

`var_dump($request->getBody()->getContents());` give  `'{"baz":"bar","foo":"bar"}'` should return `foo=bar&baz=bar` Why do we get JSON ? 

I tested from 2.6 to the latest 2.8.2, all give this result

RR app to test:

```php
<?php

use Spiral\RoadRunner\Http\PSR7Worker;
use GuzzleHttp\Psr7\HttpFactory;
use Spiral\RoadRunner\Worker;
use Spiral\Goridge\StreamRelay;

$httpFactory = new HttpFactory();

$worker = new PSR7Worker(new Worker(new StreamRelay(STDIN, STDOUT)), $httpFactory, $httpFactory, $httpFactory);

for (;;) {
    try  {
        $request = $worker->waitRequest();
    } catch (\Throwable $e) {
        $worker->respond($httpFactory->createResponse(400));
        continue;
    }

    error_log(var_export($request->getBody()->getContents(), true));

    $response = $this->app->handle($request);
    $worker->respond($response);
    $this->terminate();
}

```

The content-type does not matter, if we post json payload, from RR app we read it as a JSON containing our json payload (json in json)

**Comment by lainosantos** [comment]
@jjsaunier , Hi!

Raw body is now supported. See PR https://github.com/spiral/roadrunner-http/pull/11 :wink:

**Comment by jjsaunier** [comment]
Good job @lainosantos; unfortunately, this was a red flag for me and I'm not using rr anymore; the body should not be altered/replaced, if no explicit setting, the serialization should remain in the app logic - this broke all apps doing body forward for example, urlencode have some subtilities from one encoder to another and some parsed values are altered (%20 to + or the reverse)
